### ISSUE TITLE
Webgl not supported for mobile devices

### ISSUE THREAD

**Issue by NaveenSelva-95** [readyplayerme/Unity-WebGL-Example#11]
I have try the avatar creator in webgl template but it's not supported in mobile devices please advice me to use this in my mobile device.

**Comment by HarrisonHough** [comment]
What exactly is the issue, are you trying to build the Unity project for an Android or iOS device? 
...or build for WebGL, deploy to some URL, and then run it in the mobile browser on your mobile device?

**Comment by HarrisonHough** [comment]
couldn't replicate and issue is stale
