### ISSUE TITLE
Newtonsoft not found

### ISSUE THREAD

**Issue by xavax31** [readyplayerme/Unity-WebGL-Example#2]
Hi,

I tried to run the project in Unity 2021.2.14f1 on Mac M1 but get many errors about Newtonsoft:
Assets/Plugins/Webview/Scripts/WebView.cs(3,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

these errors appear as soon as I open project. 

something I missed?

**Comment by salvolannister** [comment]
I had the same problem, and I did a workaround that fixed everything:
- download the newest version of the rpm sdk from thei website
- export from this project a unity package with only the script and scene necessary: template folder, web help folder, the demo scene and all the scripts in "Script" folder

**Comment by HarrisonHough** [comment]
Yes, newer versions Unity now includes Newtonsoft by default. So you can just exclude/remove the Newtonsoft folder that came with our old unity SDK  (version <=1.13.2). Located in Plugins/Newtonsoft. 
However, our new SDK (2.0) no longer has this issue as it uses Unity Package manager.
