### ISSUE TITLE
RPM can't build on Unity2021 WebGL

### ISSUE THREAD

**Issue by FishWoWater** [readyplayerme/Unity-WebGL-Example#5]
I have tried a miminal RPM example but it won't build on WebGL(windows10, Unity2021, RPM 1.11.0)

I first created an empty scene and it built successfully on WebGL. Then I imported the latest RPM SDK and resolve the Newtonsoft.JSON.dll problem by refering to [tutorial](https://docs.readyplayer.me/ready-player-me/integration-guides/unity-sdk/import-and-setup). **However, when I tried to build provided examples in the SDK, it simply fails. Further, when I tried to build the original empty scene, it fails also.**

Below is the error screen shot and error lot 
![image](https://user-images.githubusercontent.com/37951601/191434209-1be899a4-2fb4-40ba-8a1e-425e31968b9a.png)

```C:\Program Files\Unity\Hub\Editor\2021.3.8f1\Editor\Data\il2cpp\build\deploy\il2cpp.exe --convert-to-cpp --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/Assembly-CSharp.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/Mono.Security.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/mscorlib.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/Newtonsoft.Json.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/ReadyPlayerMe.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/Siccity.GLTFUtility.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.Configuration.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.Core.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.Data.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.Numerics.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.Runtime.Serialization.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.Xml.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.Xml.Linq.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.AnimationModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.AudioModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.CoreModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.GridModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.ImageConversionModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.IMGUIModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.InputLegacyModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.Physics2DModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.PhysicsModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.SharedInternalsModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.SpriteShapeModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.TextCoreFontEngineModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.TextCoreTextEngineModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.TextRenderingModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.TilemapModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.UI.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.UIElementsModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.UIElementsNativeModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.UIModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.UnityWebRequestModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.UnityWebRequestTextureModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/WebView.dll --data-folder=C:/Users/55051/Desktop/metalearn/unity/RPMExample/Library/Bee/artifacts/WebGL/il2cppOutput/data --generatedcppdir=C:/Users/55051/Desktop/metalearn/unity/RPMExample/Library/Bee/artifacts/WebGL/il2cppOutput/cpp --emit-method-map --dotnetprofile=unityaot-linux --profiler-report --profiler-output-file=C:/Users/55051/Desktop/metalearn/unity/RPMExample/Library/Bee/artifacts/il2cpp_conv_x1ke.traceevents --print-command-line
Error: IL2CPP error for type 'System.Net.WebHeaderCollection/RfcChar' in assembly 'C:\Users\55051\Desktop\metalearn\unity\RPMExample\Library\Bee\artifacts\WebGL\ManagedStripped\System.dll'
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Unity.IL2CPP.CodeWriters.ChunkedMemoryStream.Seek(Int64 offset, SeekOrigin origin)
   at Unity.IL2CPP.CodeWriters.InMemoryGeneratedMethodCodeWriter.Write(IGeneratedMethodCodeStream other)
   at Unity.IL2CPP.SourceWriters.SourceWriterBase`2.FlushStream(GlobalWriteContext context, IGeneratedMethodCodeStream stream, NPath filePath)
   at Unity.IL2CPP.Contexts.Scheduling.Streams.FileLevelParallelStreamManager`3.WorkerWriteItemsToFile(WorkItemData`2 data)
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.WorkerLoop(Object data)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun ()
```
Extra information: 
* I can successfully build empty scene on WebGL
* I can build provided RPM example as a Windows PC standalone
* **It can build successfully with Unity2022**

Thanks a lot if you can provide my some suggestions (attachment is the code)
[RPMExample.zip](https://github.com/readyplayerme/Unity-WebGL-Example/files/9613789/RPMExample.zip) 

I guess one solution may be to downgrade the RPM SDK version.

**Comment by srcnalt** [comment]
Hi @FishWoWater, I was just taking a look at this issue and one thing I found is that on Unity 2021 regional format on your operating system might be causing this, that's fixed for some people who switched to English. Could you give that a try?

https://forum.unity.com/threads/i-cant-build-project-as-webgl.1339145
https://forum.unity.com/threads/failed-to-resolve-target-api-for-values.1243390/#post-7986822

**Comment by FishWoWater** [comment]
@srcnalt Thanks, I have been using Unity2022, which also solved my problem : )

By the way, do you know how to disable the `Build Warning` of RPM? It's a bit annoying, since it pops up each time I want to build something 
![image](https://user-images.githubusercontent.com/37951601/197127906-95bb2d1e-19be-41ba-a9fc-10a8e9c0c867.png)

Thanks

**Comment by srcnalt** [comment]
Yes this appears to be an issue with certain versions of Unity 2021. The idea with this popup was to notify RPM partners incase they forget to edit their partnername and go on with Demo. You can find the BuildPreprocessor script and comment out that line. And also don't hesitate to apply for a partnership. https://partnerships.readyplayer.me

**Comment by FishWoWater** [comment]
@srcnalt 
Thanks for your quick reply. But I can't find `BuildPreprocessor` script in RPM package for unity, I can only find one `Build Postprocessor`. Could you please give me some hint?  

![image](https://user-images.githubusercontent.com/37951601/197315679-4baf6b65-7dd7-43c0-bc9e-2f0d95e231c4.png)

**Comment by srcnalt** [comment]
My mistake, that one is the right script file.

**Comment by FishWoWater** [comment]
I have commented out this line, but it seems not working, stilling popping up a warning when I build the proj
![image](https://user-images.githubusercontent.com/37951601/197392130-70e984d3-f0d7-4a83-b29d-19a2490f30fa.png)

**Comment by srcnalt** [comment]
Ah this is RPM build postprocessor. I am checking the code now and it should be in `WebView` plugin PartnerPostProcessBuild.cs to be exact. You can comment out `EditorUtility.DisplayDialog` lines in the `OnPreprocessBuild` method in there.

**Comment by FishWoWater** [comment]
@srcnalt Thanks! It works!
