### ISSUE TITLE
Methods aren't available

### ISSUE THREAD

**Issue by Lorenzogasparini1975** [readyplayerme/Unity-WebGL-Example#7]
Hi, with the new version of Ready Player Me sdk is not possibile to use this method, how could I do? 
private void OnAvatarImported(GameObject avatar)
    {
        Debug.Log($"Avatar imported. [{Time.timeSinceLevelLoad:F2}]");
    }

    private void OnAvatarLoaded(GameObject avatar, AvatarMetaData metaData)
    {
        this.avatar = avatar;
        Debug.Log($"Avatar loaded. [{Time.timeSinceLevelLoad:F2}]\n\n{metaData}");
    }
Thanks
Lorenzo

**Comment by HarrisonHough** [comment]
> Hi, with the new version of Ready Player Me sdk is not possibile to use this method, how could I do? private void OnAvatarImported(GameObject avatar) { Debug.Log($"Avatar imported. [{Time.timeSinceLevelLoad:F2}]"); }
> 
> ```
> private void OnAvatarLoaded(GameObject avatar, AvatarMetaData metaData)
> {
>     this.avatar = avatar;
>     Debug.Log($"Avatar loaded. [{Time.timeSinceLevelLoad:F2}]\n\n{metaData}");
> }
> ```
> 
> Thanks Lorenzo

In the latest SDK the API has changed a little 

So instead it looks like this 

```cs
        private void Start()
        {
            avatarObjectLoader = new AvatarObjectLoader();
            avatarObjectLoader.OnCompleted += OnLoadCompleted;
        }
        
        private void OnLoadCompleted(object sender, CompletionEventArgs args)
        {
            avatar = args.Avatar;
            Debug.Log($"Avatar loaded. [{Time.timeSinceLevelLoad:F2}]\n\n{args.Metadata}");
        }
```

For more information, you can refer to our documentation 

https://docs.readyplayer.me/ready-player-me/api-reference/unity-sdk/avatarloader
